### ISSUE TITLE
Auth/AuthController

### ISSUE THREAD

**Issue by BenoitSafari** [SafariLib/SafariAPI#5]
## Task Description
Auth/permissions related. Create an _"Auth"_ controller with the following endpoints.

- [x] **Create a Login route** https://github.com/SafariLib/SafariAPI/pull/12
- [x] **Create a Logout route** https://github.com/SafariLib/SafariAPI/pull/13

#### UPDATE ⚠
- [x] **Add a configurable max login attempts** https://github.com/SafariLib/SafariAPI/pull/14

Related to https://github.com/SafariLib/SafariDoc/blob/main/project/user-stories/Authentication.md
