### ISSUE TITLE
Auth/Get user

### ISSUE THREAD

**Issue by BenoitSafari** [SafariLib/SafariAPI#7]
## Task Description
Auth/permissions related.

- [ ] **Create a GET _user_ route**
- [ ] **Create a GET _user/id_ route**
- [ ] **Create a GET _user/me_ route**
- [ ] **Create a GET _public/avatar-guid_ route**

## Technical notes
- Only admins can get another user's email
- */me* response contains the user email, but _user/id_ doesn't
- Anyone can get a user's avatar
- The _user_ (get many) route should be paginated

Related to https://github.com/SafariLib/SafariDoc/blob/main/project/user-stories/Authentication.md
